### ISSUE TITLE
g++: error: pose_estimation/build/libransac.so: No such file or directory

### ISSUE THREAD

**Issue by kevinkit** [yuxng/DA-RNN#5]
After the succesfull compiliation of KinectFusion (Step 3) we are now stuck on 4)

While there was the first error refering to numpy ("numpy/arrayobject.h not found") which could be fixed with a symbolic link a new error occurs which is a little bit harder to tackle:

when running the command 

`python setup.py build_ext --inplace`

The following error occurs:

> g++: error: pose_estimation/build/libransac.so: No such file or directory

when looking at the pose_estimation folder i found the CmakeList and so I did the following steps:
At first I installed NLOPT via : `sudo apt-get install libnlopt-dev`
And then the same procedure: 
``` 
mkdir build
cd build
cmake ..
make
```

Which resolved this issue, however is this the correct way?

**Comment by yuxng** [comment]
It is correct. The pose estimation module is added afterwards. It is not used in the original experiments in the paper.
