### ISSUE TITLE
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'ComputeflowGrad' 

### ISSUE THREAD

**Issue by kevinkit** [yuxng/DA-RNN#6]
When trying to run the shapenet experiments I get the following erros:

> InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'ComputeflowGrad' with these attrs.  Registreed devices: [CPU], Registered kernels: device = 'GPU'; T in [DT_FLOAT]. 

Then an output for the node and then ...:

> CUDA Runtime Error: no CUDA-capable device is detected 

I am using the same versiosn as you suggested for tensorflow, CUDA and all other dependencies. If I execute small test script like:

```
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```

I can see my 2 Titan 1080 GPUs mapped as devices. 

I used any kind of index for $GPU_ID, but the error is still the same. 

We really appreciate your help and thank you for your help

**Comment by yuxng** [comment]
I am not sure what causes the problem here.

**Comment by kevinkit** [comment]
I installed tensorflow via:

pip install tensorflow
pip install tensorflow-gpu


Have you installed it differently or built it by scratch?


Another difference is, that we use Ubuntu 14.04 , but this shouldn't be the cause of the problem.

**Comment by kevinkit** [comment]
We found out that the error comes from the Script:

> shapenet_scene_mutli_normal.sh

However, the code looks fine - which kind of GPU are you using? Does it provide INT8-Precision? Is it a GPU specially designed for Deep-Learning? 

Thank you really much for your help

**Comment by yuxng** [comment]
I have tested the code on Titan X (Pascal) and GeForce 1080. I can run both the scripts. Maybe check your cuda.

**Comment by kevinkit** [comment]
Changing to Ubuntu 16.04 resolvied this issue.
Also the $GPU_ID must be given as an input, when running with two cards it crashes when this parameter is left out. 

Thank you really much for your help.

**Comment by yuxng** [comment]
Good to know!
