### ISSUE TITLE
Error when make kinect_fusion (execute sh make.sh successfully)

### ISSUE THREAD

**Issue by JackHenry1992** [yuxng/DA-RNN#8]
Thks for sharing your great job. 
I've encoutered error when built kinect_fusion prj.

![image](https://user-images.githubusercontent.com/9390228/28165184-50474464-6805-11e7-86c2-bc459a79b0c4.png)
 
- fusion.h code
![image](https://user-images.githubusercontent.com/9390228/28165264-a8a1bdd8-6805-11e7-99f2-d93b4dc7df1d.png)

- rigid.h code
![image](https://user-images.githubusercontent.com/9390228/28165232-8cea574e-6805-11e7-800f-17e4e18598fc.png)

------------------------------------

It seems that sophus not found , but in my /usr/local/include/sophus exist headers of sophus and I've added this path to cmakelist.txt
![image](https://user-images.githubusercontent.com/9390228/28165380-22bbccee-6806-11e7-93dc-6229c98957ff.png)

I have no idea how to deal with this error, could you give me some tips?

**Comment by kevinkit** [comment]
see #2 looks like you have the wrong sophus version

Am 13.07.2017 14:05 schrieb "JackHenry1992" <notifications@github.com>:

**Comment by kevinkit** [comment]
did you get it to run or have you met other errors?

Am 13.07.2017 14:22 schrieb "JackHenry1992" <notifications@github.com>:

**Comment by JackHenry1992** [comment]
If built libkfusion.so successfully, 
![image](https://user-images.githubusercontent.com/9390228/28168335-57ac35aa-6811-11e7-8df4-e59fb37f2ae3.png)
but encountered pangolin error when building kinect_fusion.cpp (same with #7 ), will this influence DA-RNN system run if I don't need display result ? I run DA-RNN in docker as @kevinkit.

**Comment by kevinkit** [comment]
your screenshot looks like windows, are you on an ubuntu machine?

training etc. should work without kinect_fusion, however it may be hard to
test the data.
The scripts are provided in the repo

if you have an other way to test the output it'd be great if you may want
to share the code :)

Am 13.07.2017 15:25 schrieb "JackHenry1992" <notifications@github.com>:

**Comment by JackHenry1992** [comment]
This is my xftp screenshot. I build DA-RNN in server docker image like #7 , and encountered the same error, according to #7, it seems not easy to build kinect_fusion successfully , I have no idea now.

**Comment by jianxiongcai** [comment]
I met exactly the same problem after changing the Sophus version to the one mentioned in #2. Using the latest Sophus version (sha1: 26c200265e2eb3d76e5ab00a99ada686d6a80d15) works for me :) 

Environment: Ubuntu 16.04 with cuda 8.0

**Comment by Dinghow** [comment]
> I met exactly the same problem after changing the Sophus version to the one mentioned in #2. Using the latest Sophus version (sha1: 26c200265e2eb3d76e5ab00a99ada686d6a80d15) works for me :)
> 
> Environment: Ubuntu 16.04 with cuda 8.0

Thanks a lot! It really helps! BTW, to install the latest Sophus, I updated my eigen to 3.3.1
